version: '2'
services:
  using_entity_command-app:
    image: using_entity_command
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://using_entity_command-mysql:3306/using_entity_command?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  using_entity_command-mysql:
    extends:
      file: mysql.yml
      service: using_entity_command-mysql
